### ISSUE TITLE
Width and Height parameters are not working

### ISSUE THREAD

**Issue by IftiMahmud** [microweber/screen#10]
The Width (w) and Height (h) parameters are not really working. The given demo link (http://screen.microweber.com/shot.php?url=m.facebook.com&w=300&h=100) shows a small facebook page because it's actually small in size (mobile version), and doesn't show in 300x100 resolution. The crop/clip parameters doesn't seem like working as well.

**Comment by karlmonson** [comment]
I submitted pull request #26 that resolves this issue.

**Comment by MASNathan** [comment]
Hello @IftiMahmud 

Try this way

```php
// run:
// $ composer require microweber/screen

require_once 'vendor/autoload.php';

$websiteUrl = 'https://github.com/microweber/screen';
$fileLocation = 'screen.jpg';

$screen = new Screen\Capture($websiteUrl);
$screen
    ->setWidth(1024)
    ->setHeight(768)
    ->save($fileLocation, true);
```
