### ISSUE TITLE
take a screenshot from current edited page by user

### ISSUE THREAD

**Issue by salis77** [microweber/screen#100]
@microweber  thanks for this helpful package
I really need to let users take a screenshot from the page which they have edited...
for instance they dragged some objects or wrote something on a canvas and then they would like to download the picture of that...
is it possible to doing that with this package or anything else? (html2canvas do not support my css property so I can't use it)
please take a look at this[ stack question ](https://stackoverflow.com/questions/30942907/how-to-use-phantomjs-to-take-screen-shot-with-dynamic-data-visualization)

**Comment by peter-mw** [comment]
hi, @salis77  the thing you are trying to accomplish is maybe doable with Selenium 
This package is not appropriate for this

**Comment by salis77** [comment]
@peter-mw thanks bro but what is Selenium!? (please guide me more) and could you please answer [this issue](https://stackoverflow.com/questions/51906200/real-time-web-page-screenshot-using-phantomjs) which is related to my concern?!
