### ISSUE TITLE
Not working on linux server

### ISSUE THREAD

**Issue by miligenie** [microweber/screen#11]
Great Plugin..
Its working fine my local windows maching but when i upload on server which is linux server its not working its show binary file error!

Help needed.

**Comment by nimish1995** [comment]
how to install (where to run the command) ? 
i am using host-gator shared hosting 
PLEASE HELP

**Comment by peter-mw** [comment]
hi, you need SSH access, put the files in the `bin` folder and make them executable 

Also your PHP must be able to run the `exec` command

**Comment by nimish1995** [comment]
How to make executable 
Can you give me the code what to run and where ??
PLEASE

**Comment by peter-mw** [comment]
Run this in SSH

chmod +x /path_to_your_folder/bin/phantomjs

**Comment by codex8** [comment]
which linux os are you using ?

**Comment by nimish1995** [comment]
Don't know that i am using the shared hosting of hostgator

**Comment by codex8** [comment]
what is your domain name ?

**Comment by peter-mw** [comment]
do you have root access? also have you installed the fonts needed? 

`yum install freetype*`
