### ISSUE TITLE
Unable to capture.

### ISSUE THREAD

**Issue by codex8** [microweber/screen#16]
Unable to capture some websites like facebook.com and live.com etc...

**Comment by peter-mw** [comment]
Hi, i have disabled the live demo API as it became abused by traffic. 
You can only take screenshots from here http://screen.microweber.com/ in the demo

If you download the lib it will work on your server without restrictions

**Comment by codex8** [comment]
http://screen.microweber.com/  is also not working correctly try facebook.com and it shows black screen.
I fixed this issue i'm gonna send you request for merge.
