### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by codex8** [microweber/screen#18]
I have send you a pull request please merge code ASAP and thanks for this wonderful code :) :+1:

**Comment by peter-mw** [comment]
Hi I merged it, hope it works

**Comment by codex8** [comment]
Thanks @peter-mw

**Comment by codex8** [comment]
It's working check-> http://cloud7.ilmtechnosolutions.com/             :100:

**Comment by peter-mw** [comment]
Nice i am glad it works :)  :+1:
