### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by mikeypina** [microweber/screen#2]
http://www.urbanbeagle.com/screen/ it accepts the URL it creates several files in the jobs folder. Looking at the file severythign seems right but I do not see an image on the screen after I send submit...I have installed all the items you said to install and I changed the permissions as told.. any ideas what could be the issue?

ok looking at the .js created for this URL I see this...

var page = require('webpage').create();
 
page.viewportSize = { width: 1024, height: 768 };

page.open('http://www.sidesplitterscomedy.com/Knoxville/schedule.asp\?Page=http://www.ticketbiscuit.com/SideSplittersKnoxville/EventPage.aspx\?EID=183120\&\&\~AffTID=2\~AffID=47', function () {
    page.render('www.sidesplitterscomedy.com1648907183_1024_768.jpg');
    phantom.exit();
});

I see the url I pasted but then I see that the rendered file is definitely not going to show since its path is nowhere locally on my server which I would expect.  

I think tha tis created by your script correct?

**Comment by SivaRaman24** [comment]
This code will work on Linux OS?

**Comment by peter-mw** [comment]
@SivaRaman24 it works on linux yes
