### ISSUE TITLE
Url with param

### ISSUE THREAD

**Issue by dotMastaz** [microweber/screen#21]
Hello,
My url is : http://www.domain2.com/script.php?id=2155
I need to pass this ID.
How to pass the id with the url param ?
http://www.domain1.com/screen-master/shot.php?url=http://www.domain2.com/script.php?id=2155
or 
http://www.domain1.com/screen-master/shot.php?url=http://www.domain2.com/script.php&id=2155
Both don't work ?!
Thank you

**Comment by peter-mw** [comment]
Try with http://www.domain1.com/screen-master/shot.php?url=http://www.domain2.com/script.php%3Fid=2155

You can send URL encoded chars see the full list here http://www.degraeve.com/reference/urlencoding.php

**Comment by dotMastaz** [comment]
Thank you !

**Comment by sorinbuda** [comment]
http://www.domain1.com/screen-master/shot.php?url=http://www.domain2.com/script.php%3Fid=2155

results in

http://www.domain1.com/screen-master/shot.php?url=http://www.domain2.com/script.php^%3Fid=2155

Any ideas?
kind regards,
Sorin
