### ISSUE TITLE
Working but text are blocks..

### ISSUE THREAD

**Issue by tkima** [microweber/screen#22]
Hello, 

The function is working only and it looks nice. But it won't let me see text.. It only shows boxes. (see screenshot)

![shot php](https://cloud.githubusercontent.com/assets/12251174/7472037/64c523dc-f32e-11e4-8ee8-2f4f566a14b6.jpeg)

**Comment by peter-mw** [comment]
hi seems you dont have fonts installed

try `yum install fontconfig`

and `yum install freetype*`

**Comment by tkima** [comment]
Hello,

Thank you for the fast reply. 
I've installed the fonts like you said in the description.

But after your answer i knew where to look. 
After reading this post: 
https://stackoverflow.com/questions/15029002/phantomjs-screenshot-font-missing-boxes-rendered-instead/16033236#16033236

Ive done: yum install urw-fonts

And it now works. Thank you.
