### ISSUE TITLE
Auto Download & screenshot on the center of the page

### ISSUE THREAD

**Issue by Lucianss** [microweber/screen#29]
Is it possible to center the image? It keeps appearing in the left part of the screen..
Also is there any way to create a download button without using the auto download option?

**Comment by rachild** [comment]
I have the same problem .
I want to download with a confirmation message and in my choice directory. 
Can someone helps us  please ?

**Comment by MASNathan** [comment]
Greetings,

The ```index.php``` serves only as a demonstration of what you can do, however, one of these days I'll add some functionallity to it.
