### ISSUE TITLE
Change background from black to white

### ISSUE THREAD

**Issue by cmohanraj10** [microweber/screen#30]
How can i change black color background to white?

**Comment by sorinbuda** [comment]
In shot.php, before row 184
 page.open('{$url}', function () {

include the following code

page.evaluate(function() {
  document.body.bgColor = 'white';
});

**Comment by MASNathan** [comment]
Thank you @sorinbuda this has been added as a default as you can see [here](https://github.com/microweber/screen/blob/master/templates/screen-capture.php#L17)
