### ISSUE TITLE
Issue with execution of the script 

### ISSUE THREAD

**Issue by bologer** [microweber/screen#33]
I have problem with execution of the script. 

I have uploaded script onto: `http://domain.ru/example/Phantomjs/`:

**I am trying to** 
1. use index.php to get screenshot of the page (enter url of the page to the form ,etc) , however it just reloads the page and nothing else.
2. use shot.php with different parameters, however it does not work as well. Also it seems that shot.php has error(s), however I cannot see them.I tried `ini_set('display_errors', 1)` and `error_reporting(E_ALL)` at the beginning of the page, however none of the errors appeared. 

Am I correct that command `chmod +x bin/phantomjs` is the same if I will do `0655` file permission for the file? I tried to make permission of chmod via the SSL connection to my server and seemed to change them (as it did not show any errors, when I was doing it). But I am not sure how to check if chmod of `phantomjs` file has changed to `+x`. 

**PS.** exec() function is enabled.  

Please help me to solve this issue. 
Thank you in advance.

**Comment by MASNathan** [comment]
Hello @bologer 

Have you solved the problem? Does it still persists?

**Comment by bologer** [comment]
@MASNathan hello, no. I even tried to contact the owner of the plugin, however he did not reply. 
Have you find any solution?

**Comment by MASNathan** [comment]
The lib has been changed to OOP. You can try the following:

```php
// run $ composer require microweber/screen

require_once 'vendor/autoload.php';

$websiteUrl = 'https://github.com/microweber/screen';
$fileLocation = 'screen.jpg';

$screen = new Screen\Capture($websiteUrl);
$screen
    ->save($fileLocation, true);
```

You should also try to change the file permittions to ```755```. Here is a quick explanation [Understanding File Permissions] (https://www.maketecheasier.com/file-permissions-what-does-chmod-777-means/) .

If that still doesn´t work, check your PHP version and use this lines on the top of the file to do some debugging

```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
