### ISSUE TITLE
cannot work,it's blank

### ISSUE THREAD

**Issue by wdkwdkwdk** [microweber/screen#35]
I do everything ,chmod the bin and install the Dependencies but it just doesn't work
http://me.wdk.pw/phpsnapshot/screen/

**Comment by codex8** [comment]
this url is not working 404

**Comment by MASNathan** [comment]
Hello @wdkwdkwdk 

The url is not working.

Anyway, you can try this way

```php
// run:
// $ composer require microweber/screen

require_once 'vendor/autoload.php';

$websiteUrl = 'https://github.com/microweber/screen';
$fileLocation = 'screen.jpg';

$screen = new Screen\Capture($websiteUrl);
$screen->save($fileLocation, true);
```

If you still have no success, tell me wich OS and the PHP version you are using
