### ISSUE TITLE
URL with param

### ISSUE THREAD

**Issue by sorinbuda** [microweber/screen#40]
http://www.domain1.com/screen-master/shot.php?url=http://www.domain2.com/script.php%3Fid=2155

my IIS7 server returns

http://www.domain1.com/screen-master/shot.php?url=http://www.domain2.com/script.php^%3Fid=2155

How can I remove ^ from the IIS answer?

kind regards,
Sorin

**Comment by MASNathan** [comment]
```php
echo urlencode('http://www.domain2.com/script.php?id=2155');
// output's: http%3A%2F%2Fwww.domain2.com%2Fscript.php%3Fid%3D2155
```

**Comment by sorinbuda** [comment]
%3F returns ^? and not ? as it should
