### ISSUE TITLE
autoloader missing

### ISSUE THREAD

**Issue by whothefuckcares** [microweber/screen#42]
when installing am getting serval errors such as autoloader missing
i assume this has something todo with composer as i didn't use it for installing. 
are there noway to simply install this without installing via composer?

**Comment by MASNathan** [comment]
Hello,

I assume you get that error when using the demo files, in that case you should replace
```php
require_once '../vendor/autoload.php';
```
with
```php
require_once '../src/Capture.php';
```

if not, you can simply include the ```Capture.php```

```php
require_once 'path/to/src/Capture.php';
```

**Comment by whothefuckcares** [comment]
there we go works like a charm now 
sidenote, this screenshots very fast good job on it

**Comment by MASNathan** [comment]
Great :+1:
