### ISSUE TITLE
Follow redirects?

### ISSUE THREAD

**Issue by whothefuckcares** [microweber/screen#43]
are there anyway to easily make the screenshotter follow redirects? am sure phantomjs has some functions for it but am not very familiar with it 

if i request a screenshot from lets say adc.com it returns 301 with a valid redirection
this causes the screenshot to return an white image of nothing yet viewing the site in a the browser shows content

**Comment by MASNathan** [comment]
I'll have to look into it.

If you can fix it, please leave a PR :smile:

**Comment by MASNathan** [comment]
Was the redirect done server side or client?

I tested with a ```header('Location: ...');``` and it printed just fine.

**Comment by whothefuckcares** [comment]
server side. Use adc.com for testing

**Comment by whothefuckcares** [comment]
heres a site that does it.
http://192.71.218.174:2082 
"HTTP/1.1 301 Moved
Server: cpsrvd/11.54.0.21
Content-length: 114
Location: https://host.spyfare.com:2083/"

blank page dont redirect to spyfare

**Comment by mpaun** [comment]
Help me, pls!!!

`ini_set('error_reporting', E_ALL);
	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	
	use Screen\Capture;

	$url = 'https://github.com';

	$screenCapture = new Capture($url);
	// or
	$screenCapture = new Capture();
	$screenCapture->setUrl($url);`

error:

> Fatal error: Class 'Screen\Capture' not found in...

**Comment by MASNathan** [comment]
Hello,

have you required the autoload file ( ``require_once '../vendor/autoload.php';`` )?

**Comment by mpaun** [comment]
I can not find the file where classes are announced class . Screen\Capture
I thought that this file: `require_once '../vendor/autoload.php';`

p.s.:Sorry for my English

**Comment by MASNathan** [comment]
You need to install this dependency manager https://getcomposer.org/

or

You can require all the files that are located in the ``src`` folder.

Also don't forget to make phantomjs executable

**Comment by mpaun** [comment]
Hooray!
Indeed all the files I need are in the src folder .
But I have now arisen is another matter !
In what order to connect them to me for everything to work correctly ?

**Comment by MASNathan** [comment]
1. Capture.php
2. Location.php
3. Jobs.php
4. Output.php

**Comment by mpaun** [comment]
Oh my God

`Warning: mkdir(): Permission denied in /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/Location/Jobs.php on line 22
Fatal error: Uncaught exception 'Exception' with message 'The directory '' does not exist.' in /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/Location/Location.php:35
Stack trace: #0 /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/Location/Jobs.php(24): Screen\Location\Location->setLocation('/var/www/zalog/...') #1 /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/Capture.php(106): Screen\Location\Jobs->__construct() #2 /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/test.php(30): Screen\Capture->__construct('https://github....') #3 {main} thrown in /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/Location/Location.php on line 35`

**Comment by MASNathan** [comment]
It seems that you don't have permissions to write

**Comment by mpaun** [comment]
The head does not have to think.
The problem with write privileges decided.

Now, I copied the code from the example 'demo.php' attempts to access the script '/test.php?url=http://vk.com' and get sleduyushy

`Fatal error: Uncaught exception 'Exception' with message 'The template screen-capture does not exist!' in /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/Capture.php:160 Stack trace: #0 /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/Capture.php(146): Screen\Capture->getTemplateResult('screen-capture', Array) #1 /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/test.php(47): Screen\Capture->save('test.jpg') #2 {main} thrown in /var/www/zalog/data/www/xn--80aaoumcdc6a7bh2h.xn--p1ai/Capture.php on line 160`

**Comment by MASNathan** [comment]
Read the error please: ``Uncaught exception 'Exception' with message 'The template screen-capture does not exist!'``

Are all the template files (https://github.com/microweber/screen/blob/master/templates/screen-capture.php) in the place they should be?

**Comment by mpaun** [comment]
yes http://prntscr.com/baqwl0

**Comment by MASNathan** [comment]
All the files on this repository should be on a folder, let's say ``screen``. Make sure to download **all** the files. https://github.com/microweber/screen/archive/master.zip

Then you can copy the demo files and point them to the right location.

Make sure to make the bin executable chmod +x /path/to/screen/bin/phantomjs

The directory /path/to/screen/jobs must be writeble as well.

And also check the requirements needed https://github.com/microweber/screen#linux-requirements
