### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by rdtfyvgbnuhi** [microweber/screen#49]
am getting

Fatal error: Class 'Screen\Location\Jobs' not found in /var/www/html/Screen/src/Capture.php on line 106

i installed without composer in case that has something todo with it

**Comment by MASNathan** [comment]
Hello @rdtfyvgbnuhi 

Since composer is used to autoload the classes, that is the problem.

You can workarround that by including all the class files in this order:

1. Capture.php
2. Location.php
3. Jobs.php
4. Output.php

**Comment by rdtfyvgbnuhi** [comment]
i need to include them in the Capture.php ?
