### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by reisraff** [microweber/screen#50]
Can I get the binary of the image or just save that into a file?

**Comment by reisraff** [comment]
Other is...

Is extremely necessary to have:

FontConfig - apt-get/yum install fontconfig
FreeType - apt-get/yum install freetype*

???

**Comment by MASNathan** [comment]
Hi, it's only possible to save the image to a location, what you can do is read the file that was saved afterwards.

About the fonts, if you don't use them, the issue #51 will happen.
