### ISSUE TITLE
Doubt about Multilingual Screen Capture

### ISSUE THREAD

**Issue by kishor10d** [microweber/screen#51]
Hello,
If I am going to take screenshot of multilingual website (utf-8), then the screenshot appears with rectangular boxes instead of characters. (Please refer attached screenshot of Arabic Website)

Q. PhantomJS screen capture library worked with multilingual website screenshots or not?

![error](https://cloud.githubusercontent.com/assets/5403520/16142910/0aec7842-3487-11e6-92b9-2cb7edfcd8bf.png)

**Comment by MASNathan** [comment]
Hello,

The squares appear because you probably don't have the required fonts installed. You need to install:

**FontConfig** - apt-get/yum install fontconfig
**FreeType** - apt-get/yum install freetype*
