### ISSUE TITLE
Transparent background?

### ISSUE THREAD

**Issue by joshualambert** [microweber/screen#53]
Howdy!

Is it possible to capture a webpage where the background is transparent with this utility? I've got it installed and working great-- thanks for all your hard work! :)

**Comment by MASNathan** [comment]
Hi @joshualambert 

It's possible, but if there is no bg color set, it'll be just black.

By default the background is white, but you can change it using the [setBackgroundColor](https://github.com/microweber/screen/blob/master/src/Capture.php#L256) method.

**Comment by MASNathan** [comment]
Hello again,

The new version has a png support, this way we can screenshot the webpage with the background transparent.

Happy codding
@joshualambert

**Comment by joshualambert** [comment]
Heck yeah! Thanks dude.
