### ISSUE TITLE
Microweber does not work for all pages

### ISSUE THREAD

**Issue by abhinavpathak14** [microweber/screen#54]
Hello There,

I need to take screenshot of google website with search result.But it always returns following error:

URL: [https://www.google.co.in/?gfe_rd=cr&ei=LQODV__mNObA8gf9yryoBw&gws_rd=ssl#q=microweber](url)
Error:
Array
(
    [0] => TypeError: null is not an object (evaluating 'document.body.bgColor = '#ffffff'')
    [1] => 
    [2] =>   undefined:2
    [3] =>   :3
)

But for all other pages like github's result page, it works fine. Can someone help me what is the fix for this issue?

**Comment by peter-mw** [comment]
cant reproduce
