### ISSUE TITLE
unsupport php7

### ISSUE THREAD

**Issue by millken** [microweber/screen#56]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for microweber/screen ^1.0.1 -> satisfiable by microweber/screen[v1.0.1].
    - microweber/screen v1.0.1 requires php ~5.3 -> your PHP version (7.0.4) does not satisfy that requirement.

**Comment by peter-mw** [comment]
fixed by #57
