### ISSUE TITLE
MAC Notes

### ISSUE THREAD

**Issue by garyns** [microweber/screen#6]
Hello. Just some notes on getting shot.php working on a MAC (Mavericks). This was with an XAMPP server.

- install phantomjs (eg via brew package installer)
- find where phantomjs is installed (brew list phantomjs)
- Update $bin_files to point the that directory
- $escaped_command = "unset DYLD_LIBRARY_PATH; " . escapeshellcmd($exec); 
This was needed to get around the error (in apache error log) "dyld: Symbol not found: __cg_jpeg_resync_to_restart..." (source: http://stackoverflow.com/questions/19008960/phantomjs-on-mac-os-x-works-from-the-command-line-not-via-exec)

**Comment by Prosparky** [comment]
Hi, I have tried installing screen as you suggested, but no images are caching to display in the iframe. I am running it on Mamp from a mac. I have made phantomjs executable, installed the dependencies and the folders including the cache is set to 777. @peter-mw @garyns Can you help?

**Comment by peter-mw** [comment]
Hi @Prosparky i do not have mac at my hands and i can't test. 
If @garyns or someone with mac can debug it please post here

**Comment by garyns** [comment]
Hi,

I have not used screens since my original post. I just installed it and got it working on El Captain.

I'm not sure what steps you have taken, however this is what I just did.

The bin/phantomjs that ships with screens is for linux, not Mac, so a Mac version needs to be installed and shot.php need to be updated to use it.
 
- install phantomjs (eg brew install phantomjs, or with npm).
- make sure you can execute phantomjs in the terminal.
- find the bin folder where phantomjs is installed (eg brew list phantomjs, or locate phantomjs).
- edit shot.php and replace $bin_files. Here is what mine looks like. We just want the 'bin' folder, not the full path to the phantomjs binary.
```
//$bin_files = $here . 'bin' . DIRECTORY_SEPARATOR;
$bin_files = "/usr/local/Cellar/phantomjs/2.0.0/bin" . DIRECTORY_SEPARATOR;
```
- Now browse to index.php and take a screenshot.

If that fails, check this:
in shot php approx line 119, echo out $escaped_command and then exit.
```
 $escaped_command = escapeshellcmd($exec);
echo $escaped_command; exit;   // <------------ ADD THIS LINE
exec($escaped_command);
```
Reload index.php and try a screen shot. Now you should see the command that PHP is trying to execute. If phantomjs is installed correctly, you should be able to copy this command and paste it into the terminal and successfully execute it. (the image would be saved in the cwd, not cache).

I hope this helps.
Gary.

**Comment by Prosparky** [comment]
HI @garyns 

Thank you so much for your help and detailed instructions, I now have it working after a doh! moment.

I forgot to remove $here . on line 26 so phantomjs was being pointed in the wrong direction. 

Thanks again 
Mark
