### ISSUE TITLE
Prevent Analytics Triggering

### ISSUE THREAD

**Issue by Failcookie** [microweber/screen#82]
I have been trying out the code and it works great! I am currently using it in paired with a web crawler for sites who volunteer the crawl. I'd like to be able to render a web page without freaking out the users analytics, but I am struggling with ways to do that.

I found a Stackoverflow question similar to the issue, but I am not seeing how I can implement it within this container. Here is the link: http://stackoverflow.com/questions/22274112/is-there-a-way-to-disable-google-analytics-tracking-in-phantomjs

Has anyone discovered a way to do this? Or is it just not possible right now?

**Comment by MASNathan** [comment]
Hello @Failcookie

Following the example that you provided on StackOverflow you can easily add the following code to the template file https://github.com/microweber/screen/blob/master/templates/screen-capture.php#L16

```js
page.onResourceRequested = function(requestData, request) {
    if ((/http:\/\/.+?\.css/gi).test(requestData['url']) || requestData.headers['Content-Type'] == 'text/css') {
        console.log('The url of the request is matching. Aborting: ' + requestData['url']);
        request.abort();
    }
};
```

Source: https://github.com/ariya/phantomjs/blob/master/examples/loadurlwithoutcss.js#L12

If you manage to tackle this issue feel free to submit a PR.
