### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ezekel** [microweber/screen#96]
I am having problem when I run my code

> /var/www/myproject/vendor/microweber/screen/bin/phantomjs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

Here is my system 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Thank you in advance.

**Comment by cstpraveen** [comment]
Try installing Phantomjs in your machine and try something like `$capture->setBinPath($binPath);`

$binPath = Your bin path where the phantomjs located.
